# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compression.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'compression.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ompression.proto\x12\x0b\x63ontextmesh\"\xbc\x01\n\x0f\x43ompressRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x11\n\ttool_name\x18\x03 \x01(\t\x12\x16\n\x0etool_args_json\x18\x04 \x01(\t\x12\x12\n\nraw_output\x18\x05 \x01(\t\x12\x18\n\x10task_description\x18\x06 \x01(\t\x12\x14\n\x0crecent_steps\x18\x07 \x03(\t\x12\x15\n\rbudget_tokens\x18\x08 \x01(\x05\"\xdb\x01\n\x10\x43ompressResponse\x12\x19\n\x11\x63ompressed_output\x18\x01 \x01(\t\x12\x17\n\x0foriginal_tokens\x18\x02 \x01(\x05\x12\x19\n\x11\x63ompressed_tokens\x18\x03 \x01(\x05\x12\x19\n\x11\x63ompression_ratio\x18\x04 \x01(\x02\x12\x17\n\x0f\x63hunks_selected\x18\x05 \x01(\x05\x12\x14\n\x0c\x63hunks_total\x18\x06 \x01(\x05\x12\x10\n\x08trace_id\x18\x07 \x01(\t\x12\x1c\n\x14\x63hunk_types_selected\x18\x08 \x03(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa0\x01\n\x12\x43ompressionService\x12G\n\x08\x43ompress\x12\x1c.contextmesh.CompressRequest\x1a\x1d.contextmesh.CompressResponse\x12\x41\n\x06Health\x12\x1a.contextmesh.HealthRequest\x1a\x1b.contextmesh.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compression_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPRESSREQUEST']._serialized_start=35
  _globals['_COMPRESSREQUEST']._serialized_end=223
  _globals['_COMPRESSRESPONSE']._serialized_start=226
  _globals['_COMPRESSRESPONSE']._serialized_end=445
  _globals['_HEALTHREQUEST']._serialized_start=447
  _globals['_HEALTHREQUEST']._serialized_end=462
  _globals['_HEALTHRESPONSE']._serialized_start=464
  _globals['_HEALTHRESPONSE']._serialized_end=496
  _globals['_COMPRESSIONSERVICE']._serialized_start=499
  _globals['_COMPRESSIONSERVICE']._serialized_end=659
# @@protoc_insertion_point(module_scope)
